version: '3.8'

services:
    kong-database:
        image: postgres:13
        environment:
            POSTGRES_DB: kong
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: kongpass
        volumes:
            - kong-data:/var/lib/postgresql/data
        networks:
            - kong-net

    kong-migrations:
        image: kong/kong-gateway:3.7.0.0
        depends_on:
            - kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kongpass
            KONG_PASSWORD: test
        entrypoint: ['/bin/sh', '-c']
        command: 'kong migrations bootstrap'
        networks:
            - kong-net

    kong:
        image: kong/kong-gateway:3.7.0.0
        depends_on:
            - kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kongpass
            KONG_PASSWORD: test
        ports:
            - '8000:8000'
            - '8443:8443'
            - '8001:8001'
            - '8444:8444'
        networks:
            - kong-net

    store-api:
        image: chauvanloc/store-api
        ports:
            - 4003:3003
        env_file:
            - .env
            - .env.store
            - .env.aws
            - .env.rabbitmq
            - .env.bullqueue
            - .env.elasticsearch
        networks:
            - kong-net

networks:
    kong-net:
        driver: bridge

volumes:
    kong-data:
