version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - mysql_microservice:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=microservice
      - MYSQL_USER=vanloc
      - MYSQL_PASSWORD=123123
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - rabbitmq_microservice:/var/lib/rabbitmq
    ports:
      - 6000:6000
    environment:
      - RABBITMQ_DEFAULT_USER=vanloc
      - RABBITMQ_DEFAULT_PASS=123123

volumes:
  mysql_microservice:
  rabbitmq_microservice:
