version: '3.8'

services:
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=123123
            - MYSQL_DATABASE=microservice
            - MYSQL_USER=vanloc
            - MYSQL_PASSWORD=123123
        networks:
            - kong-net

    rabbitmq:
        container_name: rabbitmq1
        image: rabbitmq:3-management
        restart: unless-stopped
        volumes:
            - user_rabbitmq_data:/var/lib/rabbitmq
        ports:
            - 5700:5672
            - 17000:15672
        environment:
            - RABBITMQ_DEFAULT_USER=vanloc
            - RABBITMQ_DEFAULT_PASS=123123
        networks:
            - kong-net

    redis:
        container_name: redis1
        image: redis
        restart: unless-stopped
        volumes:
            - redis_data:/data
        ports:
            - 6400:6379
        networks:
            - kong-net

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'discovery.type=single-node'
            - ELASTIC_PASSWORD=123123
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es01_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - kong-net

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - kong-net

    store-api:
        image: chauvanloc/store-api:latest
        container_name: store-api
        ports:
            - 4003:3003
        env_file:
            - .env
            - .env.store
            - .env.aws
            - .env.rabbitmq
            - .env.bullqueue
            - .env.elasticsearch
        depends_on:
            - mysql
        networks:
            - kong-net

networks:
    kong-net:
        driver: bridge

volumes:
    mysql_data:
    user_rabbitmq_data:
    product_rabbitmq_data:
    redis_data:
    es01_data:
    kong-data:
