version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql1
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=microservice
      - MYSQL_USER=vanloc
      - MYSQL_PASSWORD=123123
  rabbitmq:
    container_name: rabbitmq1
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - user_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5700:5672
      - 17000:15672
    environment:
      - RABBITMQ_DEFAULT_USER=vanloc
      - RABBITMQ_DEFAULT_PASS=123123
  redis:
    container_name: redis1
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6400:6379
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql_data:
  user_rabbitmq_data:
  product_rabbitmq_data:
  redis_data:
